### ISSUE TITLE
i can help you revive isd279 games

### ISSUE THREAD

**Issue by 25HoursaDay** [ReedGraf/ReedGraf.GitHub.io#1]
dude, if you want i can shout you out on my site for free, if you make a new site that is. thatll revive isd279games. just ask

**Comment by 25HoursaDay** [comment]
ill link the new site as an announcement on mine

**Comment by ReedGraf** [comment]
No, it cannot be done. There were IRL complications and the site had to be shut down. I cannot legally put it back up.
